##define your subdir_y subdir_m and obj_y

CC_CFLAGS += -I./include -g

subdir_y += 
subdir_m +=

obj_y +=
obj_y += uv_task.o
obj_y += uv_context.o
# obj_y += uv_main.o //for demo

asm_y += asm.o

include $(TOP_DIR)/MakeRule

