##define your subdir_y subdir_m and obj_y

subdir_y += 

subdir_m +=

obj_y +=
obj_y += hello.o
obj_y += uviot_log.o
obj_y += uviot_event.o
obj_y += uviot_module.o

include $(TOP_DIR)/MakeRule
