##define your subdir_y subdir_m and obj_y

subdir_y += 

subdir_m +=

obj_y +=
obj_y += uviot.o
obj_y += uviot_log.o
obj_y += uviot_section.o
obj_y += uviot_module.o
obj_y += uviot_obj.o
obj_y += uviot_msg.o
obj_y += uviot_conn.o

include $(TOP_DIR)/MakeRule
