##define your subdir_y subdir_m and obj_y

subdir_y += 
subdir_m +=

obj_y +=
obj_y += uvco_task.o
obj_y += uvco_context.o

# obj_y += uv_main.o //for demo

asm_y += asm.o

include $(TOP_DIR)/MakeRule

