##define your subdir_y subdir_m and obj_y

subdir_y += task

subdir_m += lib

obj_y +=
obj_y += uvco.o
obj_y += uvco_log.o
obj_y += uvco_section.o
obj_y += uvco_module.o
obj_y += uvco_node.o
obj_y += uvco_conn.o
obj_y += uvco_stream.o
obj_y += uvco_diag.o

include $(TOP_DIR)/MakeRule
